"""新增百科的稳定身份与中文界面说明，不依赖 Django 模型。"""

DOMAINS = (('plan', 'PlanNode', 'plan_node', '执行计划节点', 'plan', 'sql', '个节点', '执行计划节点的输入输出、执行策略、资源行为、并行接口与示例。'),
 ('operator',
  'PgOperator',
  'pg_operator_entry',
  '运算符',
  'operator',
  'func',
  '个重载',
  '按操作数签名区分的运算符重载、结果类型、实现函数与索引成员关系。'),
 ('opclass',
  'OperatorClass',
  'operator_class',
  '运算符族',
  'opclass',
  'cat',
  '个条目',
  '索引运算符类与族、策略运算符及支持函数的逐版本定义。'),
 ('fdw',
  'ForeignDataWrapper',
  'foreign_data_wrapper',
  '外部数据包装器',
  'fdw',
  'cat',
  '个包装器',
  '外部数据访问、读写与下推能力、事务行为以及扩展来源证据。'),
 ('tableam',
  'TableAccessMethod',
  'table_am',
  'Table AM',
  'tableam',
  'cat',
  '种方法',
  '表访问方法的元组组织、MVCC、维护接口与实现边界。'),
 ('psql', 'PsqlCommand', 'psql_command', 'psql 命令', 'psql', 'sql', '条命令', '反斜杠命令的完整语法、修饰符、示例与客户端版本变化。'),
 ('tool', 'CommandLineTool', 'command_tool', '命令行工具', 'tool', 'sql', '个工具', '客户端和服务端程序、命令选项、环境变量及操作示例。'),
 ('conn',
  'ConnectionParameter',
  'connection_parameter',
  '连接参数',
  'conn',
  'guc',
  '个参数',
  'libpq 连接关键字、环境变量、默认值与优先级。'),
 ('metric',
  'StatisticsMetric',
  'statistics_metric',
  '统计与指标',
  'metric',
  'wait',
  '个字段',
  '逐字段的统计视图与进度指标，保留定义、单位及重置上下文。'),
 ('storage',
  'StorageStructure',
  'storage_structure',
  '存储结构',
  'storage',
  'cat',
  '种结构',
  '数据库文件、关系分叉、页、元组、TOAST、空闲空间映射与可见性映射。'),
 ('protocol',
  'ProtocolMessage',
  'protocol_message',
  '协议消息',
  'protocol',
  'sql',
  '种消息',
  '前后端消息方向、线上字段与对应版本的协议定义。'),
 ('language',
  'ProceduralLanguage',
  'procedural_language',
  '过程语言',
  'language',
  'func',
  '种语言',
  '内置过程语言、处理函数、信任边界及编程接口。'),
 ('fts',
  'TextSearchComponent',
  'text_search_component',
  '全文检索组件',
  'fts',
  'func',
  '个组件',
  '全文检索解析器、词典、模板和配置的核心源定义。'),
 ('auth',
  'AuthenticationMethod',
  'authentication_method',
  '认证方法',
  'auth',
  'err',
  '种方法',
  '客户端认证方法、配置要求与版本行为。'),
 ('locale',
  'CollationEncoding',
  'collation_encoding',
  '排序规则与编码',
  'locale',
  'cat',
  '个条目',
  '服务端编码、排序规则提供者及操作系统和构建相关边界。'),
 ('decode',
  'LogicalDecodingPlugin',
  'logical_decoding_plugin',
  '逻辑解码插件',
  'decode',
  'func',
  '个插件',
  '逻辑解码输出插件、格式、选项及各自实现的来源证据。'))
DOMAIN_KEYS = tuple(row[0] for row in DOMAINS)

DOMAIN_NOTES = {'plan': '核心计划节点与同版 EXPLAIN 和执行器分派核对。文本策略、并行或部分聚合修饰符是节点属性；手册示例不代表新的性能测量。',
 'operator': '每个核心重载按操作数签名独立收录。运算符族成员关系只证明特定策略或排序用途，并不保证任意查询都能使用索引。',
 'opclass': '运算符类与族是独立对象。族内可以包含跨类型运算符；策略编号及支持函数编号的含义取决于索引方法。扩展创建的对象不属于核心清单。',
 'fdw': '核心包装器按 PostgreSQL 版本采样。扩展目录记录使用独立的采集日期与项目版本。分类及声明的兼容性不能证明具体能力；缺少证据时明确显示未知。',
 'tableam': 'Table AM 表访问方法接口始于 PostgreSQL 12。更早版本的堆存储不作为这一后续 API 的实现。FDW、数据库分支和其他存储架构分别标识。',
 'psql': '版本选择指 psql 客户端构建。反斜杠命令区分大小写，例如 \\dD 与 \\dd 不同；相关写法可能共用手册语法块。',
 'tool': '选项和示例属于所选程序构建。客户端与服务端版本可能不同；跨版本操作应核对该版兼容性说明。',
 'conn': '这些是 libpq 客户端连接关键字，与服务端 GUC 分开。仅有源码的关键字与编译默认表达式保留来源标识，不当作实测生效值。',
 'metric': '每个字段保留所在视图及来源上下文。只有证据支持时才标注单位、采集方式和重置行为。示例查询不代表实测值，当前状态字段不当作累计计数器。',
 'storage': '清单覆盖手册中的物理结构和 PGDATA 路径，不枚举所有内部 C 结构。页大小、对齐与访问方法的布局受构建影响；图示为概念示意。',
 'protocol': '前后端协议消息与逻辑复制载荷分别标识，定义保留条件和重复字段。字段顺序不等于字节偏移；交互章节说明合法消息交换。',
 'language': '清单描述随核心发布的语言、处理函数及可信和不可信变体，不表示某个数据库已安装或启用这些语言。',
 'fts': '核心解析器、模板、词典与配置包含生成的 Snowball 条目和词元映射。数据库本地配置变更及扩展对象不属于初始化快照。',
 'auth': '认证方法与同版本服务端源码和 HBA 手册核对。可用性、传输要求及凭据处理取决于方法与构建。',
 'locale': '编码标识符、排序规则提供者和显式初始化的排序规则分别收录。操作系统与 ICU 的地区设置因安装环境而异，并非通用完整清单。仅客户端可用的编码与服务端编码分别标识。',
 'decode': '核心输出插件使用 PostgreSQL 版本证据，扩展格式和能力使用独立日期与固定项目来源。目录分类不能证明协议兼容性。'}
