from django.db import migrations


# A local replica of the two PGEXT tables. Category labels are presentation
# constants; no foreign key or runtime query needs other PGEXT tables.
class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [migrations.RunSQL(
        sql="""
CREATE SCHEMA IF NOT EXISTS pgext;

CREATE TABLE pgext.universe (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL,
    pkg text NOT NULL,
    lead_ext text NOT NULL,
    category text NOT NULL,
    packaged boolean DEFAULT false NOT NULL,
    lifecycle text,
    kind text NOT NULL,
    kernel text,
    vendor text,
    contrib boolean DEFAULT false NOT NULL,
    lang text NOT NULL,
    license text,
    tags text[],
    version text,
    url text NOT NULL,
    repo_url text,
    home_url text,
    doc_url text,
    license_url text,
    control_url text,
    author_url text,
    cargo_url text,
    pgxn_url text,
    has_bin boolean,
    has_lib boolean,
    need_ddl boolean DEFAULT true NOT NULL,
    need_load boolean,
    trusted boolean,
    relocatable boolean,
    libs text[],
    schemas text[],
    pg_ver text[],
    requires text[],
    required_by text[],
    see_also text[],
    tarball text,
    pgrx_ver text,
    rpm_ver text,
    rpm_repo text,
    rpm_pkg text,
    rpm_pg smallint[],
    rpm_deps text[],
    rpm_build boolean DEFAULT false NOT NULL,
    deb_ver text,
    deb_repo text,
    deb_pkg text,
    deb_pg smallint[],
    deb_deps text[],
    deb_build boolean DEFAULT false NOT NULL,
    stars integer,
    watchers integer,
    forks integer,
    repo_created_at date,
    last_commit date,
    last_release date,
    last_active date,
    checked_at date,
    en_desc text,
    zh_desc text,
    comment text,
    extra jsonb DEFAULT '{}'::jsonb NOT NULL,
    mtime date DEFAULT CURRENT_DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE pgext.doc (
    id integer NOT NULL,
    ext text NOT NULL,
    pkg text NOT NULL,
    repo_url text,
    license_url text,
    control_url text,
    author_url text,
    home_url text,
    cargo_url text,
    en_doc text,
    zh_doc text,
    PRIMARY KEY (id),
    UNIQUE (ext)
);
""",
        reverse_sql="DROP TABLE pgext.doc; DROP TABLE pgext.universe;",
    )]
