# Generated by Django 5.2.17 on 2026-09-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_docpageredirect'),
    ]

    # Freeze the reviewed DDL here: Django's implicit LIKE indexes are unnecessary.
    # State operations keep the migration graph and ORM models synchronized.
    operations = [
        migrations.RunSQL(
            sql="""
-- Third-party Markdown documentation; PostgreSQL's own docs remain independent.
-- The caller owns the transaction and search_path.

CREATE TABLE doc_project (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(64) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    license text DEFAULT NULL,
    upstream_url varchar(2048) NOT NULL DEFAULT '',
    meta jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE doc_revision (
    -- Assigned by the importer, e.g. pgbouncer-1.1.1-zh.
    id text PRIMARY KEY,
    project_id varchar(64) NOT NULL,
    version varchar(64) NOT NULL,
    lang varchar(32) NOT NULL,
    name varchar(256) NOT NULL DEFAULT '',
    upstream_url varchar(2048) NOT NULL DEFAULT '',
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT doc_revision_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES doc_project (slug)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doc_revision_project_version_lang_key
        UNIQUE (project_id, version, lang)
);

CREATE TABLE doc_page (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rev_id text NOT NULL,
    -- Empty path is the manual home page.
    path varchar(512) NOT NULL DEFAULT '',
    -- Source-relative link base, e.g. README.md or guide/setup.md.
    source_path varchar(512) NOT NULL,
    upstream_url varchar(2048) NOT NULL DEFAULT '',
    title varchar(256) NOT NULL,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    description text NOT NULL DEFAULT '',
    content text NOT NULL,

    CONSTRAINT doc_page_rev_id_fkey
        FOREIGN KEY (rev_id) REFERENCES doc_revision (id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doc_page_rev_path_key
        UNIQUE (rev_id, path),
    CONSTRAINT doc_page_rev_source_path_key
        UNIQUE (rev_id, source_path)
);

COMMENT ON COLUMN doc_project.license IS
    'Default documentation license; NULL means unknown. A revision may override it in meta.license.';
""",
            reverse_sql="""
DROP TABLE doc_page;
DROP TABLE doc_revision;
DROP TABLE doc_project;
""",
            state_operations=[
                migrations.CreateModel(
                    name='DocProject',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('slug', models.CharField(max_length=64, unique=True)),
                        ('name', models.CharField(max_length=100)),
                        ('license', models.TextField(blank=True, db_comment='Default documentation license; NULL means unknown. A revision may override it in meta.license.', db_default=None, default=None, null=True)),
                        ('upstream_url', models.CharField(blank=True, db_default='', default='', max_length=2048)),
                        ('meta', models.JSONField(db_default={}, default=dict)),
                    ],
                    options={
                        'db_table': 'doc_project',
                    },
                ),
                migrations.CreateModel(
                    name='DocRevision',
                    fields=[
                        ('id', models.TextField(primary_key=True, serialize=False)),
                        ('version', models.CharField(max_length=64)),
                        ('lang', models.CharField(max_length=32)),
                        ('name', models.CharField(blank=True, db_default='', default='', max_length=256)),
                        ('upstream_url', models.CharField(blank=True, db_default='', default='', max_length=2048)),
                        ('meta', models.JSONField(db_default={}, default=dict)),
                        ('project', models.ForeignKey(db_column='project_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisions', to='docs.docproject', to_field='slug')),
                    ],
                    options={
                        'db_table': 'doc_revision',
                    },
                ),
                migrations.CreateModel(
                    name='EcosystemDocPage',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('path', models.CharField(blank=True, db_default='', default='', max_length=512)),
                        ('source_path', models.CharField(max_length=512)),
                        ('upstream_url', models.CharField(blank=True, db_default='', default='', max_length=2048)),
                        ('title', models.CharField(max_length=256)),
                        ('meta', models.JSONField(db_default={}, default=dict)),
                        ('description', models.TextField(blank=True, db_default='', default='')),
                        ('content', models.TextField()),
                        ('rev', models.ForeignKey(db_column='rev_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='docs.docrevision')),
                    ],
                    options={
                        'db_table': 'doc_page',
                    },
                ),
                migrations.AddConstraint(
                    model_name='docrevision',
                    constraint=models.UniqueConstraint(fields=('project', 'version', 'lang'), name='doc_revision_project_version_lang_key'),
                ),
                migrations.AddConstraint(
                    model_name='ecosystemdocpage',
                    constraint=models.UniqueConstraint(fields=('rev', 'path'), name='doc_page_rev_path_key'),
                ),
                migrations.AddConstraint(
                    model_name='ecosystemdocpage',
                    constraint=models.UniqueConstraint(fields=('rev', 'source_path'), name='doc_page_rev_source_path_key'),
                ),
            ],
        ),
    ]
