# Generated by Django 5.2.17 on 2026-09-11 01:55

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('sqlstate', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('condition_name', models.TextField(blank=True, default='')),
                ('condition_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('macros', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('primary_macro', models.TextField(blank=True, default='')),
                ('severity_classes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('status', models.TextField(default='active')),
                ('introduced', models.JSONField(blank=True, null=True)),
                ('removed', models.JSONField(blank=True, null=True)),
                ('known_present_by', models.TextField(blank=True, default='')),
                ('present_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('preview_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('depth', models.TextField(default='reference')),
                ('editorial_review', models.TextField(blank=True, default='')),
                ('runtime_verification', models.TextField(blank=True, default='')),
                ('evidence_tier', models.TextField(blank=True, default='')),
                ('case_count', models.IntegerField(default=0)),
                ('snippet_count', models.IntegerField(default=0)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('source_rev', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wiki_errcode',
                'ordering': ('klass', 'sqlstate'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeClass',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('sqlstate_count', models.IntegerField(default=0)),
                ('severity_classes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'wiki_errcode_class',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeRelease',
            fields=[
                ('major', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='formal', max_length=8)),
                ('release', models.TextField(blank=True, default='')),
                ('tag', models.TextField(blank=True, default='')),
                ('commit', models.CharField(blank=True, default='', max_length=40)),
                ('path', models.TextField(blank=True, default='')),
                ('code_count', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'wiki_errcode_release',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.TextField()),
                ('versions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('preconditions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('trigger', models.TextField(blank=True, default='')),
                ('assertions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('repair', models.TextField(blank=True, default='')),
                ('cleanup', models.TextField(blank=True, default='')),
                ('has_snippet', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_case',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.TextField()),
                ('statement', models.TextField()),
                ('method', models.TextField(blank=True, default='')),
                ('limits', models.TextField(blank=True, default='')),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('runtime', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_claim',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.AddField(
            model_name='errorcode',
            name='klass',
            field=models.ForeignKey(db_column='class_code', on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='wiki.errorcodeclass'),
        ),
        migrations.CreateModel(
            name='ErrorCodeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField()),
                ('severity', models.TextField(blank=True, default='')),
                ('path', models.TextField(blank=True, default='')),
                ('limits', models.TextField(blank=True, default='')),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_message',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodePresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(default='modern', max_length=8)),
                ('start', models.TextField(blank=True, default='')),
                ('end', models.TextField(blank=True, default='')),
                ('start_tag', models.TextField(blank=True, default='')),
                ('end_tag', models.TextField(blank=True, default='')),
                ('start_major', models.TextField(blank=True, default='')),
                ('end_major', models.TextField(blank=True, default='')),
                ('evidence_count', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_presence',
                'ordering': ('errcode', 'era', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeRuntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_id', models.TextField()),
                ('run_id', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('target', models.TextField(blank=True, default='')),
                ('server_version', models.TextField(blank=True, default='')),
                ('cases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('limits', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_runtime',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.TextField()),
                ('kind', models.TextField(blank=True, default='')),
                ('tag', models.TextField(blank=True, default='')),
                ('commit', models.CharField(blank=True, default='', max_length=40)),
                ('path', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('docs_url', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.IntegerField(default=0)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_source',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', '主消息'), ('detail', 'DETAIL'), ('hint', 'HINT'), ('context', 'CONTEXT')], max_length=12)),
                ('role', models.TextField(blank=True, default='')),
                ('template', models.TextField()),
                ('literal', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='wiki.errorcode')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='wiki.errorcodemessage')),
            ],
            options={
                'db_table': 'wiki_errcode_template',
                'ordering': ('errcode', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ErrorCodeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('body_md', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('translation_source_rev', models.TextField(blank=True, default='')),
                ('is_stale', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('errcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='wiki.errorcode')),
            ],
            options={
                'db_table': 'wiki_errcode_text',
                'ordering': ('errcode', 'lang'),
            },
        ),
        migrations.AddIndex(
            model_name='errorcode',
            index=models.Index(fields=['klass', 'sqlstate'], name='wiki_errcode_class_order'),
        ),
        migrations.AddIndex(
            model_name='errorcode',
            index=models.Index(fields=['evidence_tier'], name='wiki_errcode_tier'),
        ),
        migrations.AddIndex(
            model_name='errorcode',
            index=models.Index(fields=['condition_name'], name='wiki_errcode_condition'),
        ),
        migrations.AddIndex(
            model_name='errorcodepresence',
            index=models.Index(fields=['errcode', 'era'], name='wiki_errcode_presence_era'),
        ),
        migrations.AddIndex(
            model_name='errorcodetemplate',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wiki_errcode_tpl_vector'),
        ),
        migrations.AddIndex(
            model_name='errorcodetemplate',
            index=models.Index(fields=['errcode', 'kind'], name='wiki_errcode_tpl_kind'),
        ),
        migrations.AddIndex(
            model_name='errorcodetext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wiki_errcode_text_vector'),
        ),
        migrations.AddConstraint(
            model_name='errorcodetext',
            constraint=models.UniqueConstraint(fields=('errcode', 'lang'), name='wiki_errcode_text_lang'),
        ),
    ]
