# Generated by Django 5.2.17 on 2026-09-11 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_errcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('major', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('support_status', models.TextField(blank=True, default='')),
                ('source_tag', models.TextField(blank=True, default='')),
                ('documentation_version', models.TextField(blank=True, default='')),
                ('release', models.TextField(blank=True, default='')),
                ('doc_slug', models.TextField(blank=True, default='')),
                ('relation_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('kinds', models.JSONField(blank=True, default=dict)),
                ('runtime_verified', models.BooleanField(default=False)),
                ('schema_source', models.TextField(blank=True, default='')),
                ('transition', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'wiki_catalog_version',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CatalogRelation',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=12)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_zh', models.TextField(blank=True, default='')),
                ('first_version', models.CharField(blank=True, default='', max_length=8)),
                ('last_version', models.CharField(blank=True, default='', max_length=8)),
                ('present_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('changed_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('column_count', models.IntegerField(default=0)),
                ('relation_oid', models.IntegerField(blank=True, null=True)),
                ('relkind', models.CharField(blank=True, default='', max_length=1)),
                ('shared', models.BooleanField(default=False)),
                ('versions', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('position', models.IntegerField(default=0)),
                ('source_rev', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wiki_catalog',
                'ordering': ('position',),
                'indexes': [models.Index(fields=['kind', 'name'], name='wiki_catalog_kind')],
            },
        ),
    ]
