# Generated by Django 5.2.17 on 2026-09-25 07:31

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


from ._reference_documents import verify, restore_children


class Migration(migrations.Migration):
    dependencies = [('wiki', '0009_reference_table_names'), ('search', '0005_catalog_entry_identity')]
    operations = [
        migrations.RunPython(verify, restore_children),
        migrations.DeleteModel(name='ErrorCodeTemplate'),
        migrations.DeleteModel(name='ErrorCodeText'),
        migrations.DeleteModel(name='ErrorCodePresence'),
        migrations.DeleteModel(name='ErrorCodeCase'),
        migrations.DeleteModel(name='ErrorCodeClaim'),
        migrations.DeleteModel(name='ErrorCodeSource'),
        migrations.DeleteModel(name='ErrorCodeRuntime'),
        migrations.DeleteModel(name='ErrorCodeMessage'),
        migrations.AddConstraint(
            model_name='errorcode',
            constraint=models.CheckConstraint(condition=models.Q(('sqlstate__regex', '^[0-9A-Z]{5}$')), name='sqlstate_code_format'),
        ),
        migrations.AddConstraint(
            model_name='errorcode',
            constraint=models.CheckConstraint(condition=models.Q(('klass_id', django.db.models.functions.text.Left('sqlstate', 2))), name='sqlstate_class_prefix'),
        ),
        migrations.AddConstraint(
            model_name='errorcode',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('facts'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='sqlstate_facts_object'),
        ),
        migrations.AddConstraint(
            model_name='errorcode',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('texts'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='sqlstate_texts_object'),
        ),
        migrations.AddConstraint(
            model_name='errorcode',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(models.Func(models.F('evidence'), function='jsonb_typeof', output_field=models.CharField()), models.Value('object')), name='sqlstate_evidence_object'),
        ),
    ]
