# Generated by Django 5.2.17 on 2026-09-26 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_lockmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionHook',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hook',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectIdentifierType',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oid_type',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredefinedRole',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'predefined_role',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageParameter',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'relopt',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
    ]
