# Generated by Django 5.2.17 on 2026-09-29 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_reference_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_type',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexAccessMethod',
            fields=[
                ('slug', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_zh', models.TextField()),
                ('category', models.TextField()),
                ('summary', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('versions', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'index_am',
                'ordering': ('category', 'name', 'slug'),
                'abstract': False,
            },
        ),
    ]
