# Generated by Django 3.2.10 on 2026-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurematrix', '0010_feature_v17'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='v18',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Obsolete'), (3, '?')], default=0, verbose_name='18'),
        ),
        migrations.RunSQL("UPDATE featurematrix_feature SET v18=v17"),
    ]
