# Generated by Django 5.2.17 on 2026-09-09 04:30

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0004_docpageredirect'),
    ]

    operations = [
        # pg_trgm may already serve other applications; reversal must not remove it.
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='IndexedPage',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='docs.docpage')),
                ('source_hash', models.CharField(max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, max_digits=3)),
                ('key', models.CharField(max_length=64)),
                ('entity_key', models.TextField()),
                ('kind', models.CharField(max_length=16)),
                ('subtype', models.CharField(blank=True, max_length=32)),
                ('name', models.TextField()),
                ('name_key', models.TextField()),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('anchor', models.TextField(blank=True)),
                ('heading', models.TextField()),
                ('signature', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('preview', models.TextField()),
                ('vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='search.indexedpage')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'kind', 'name_key'], name='docsearch_scope_kind'), models.Index(fields=['name_key'], name='docsearch_name_prefix', opclasses=('text_pattern_ops',)), django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='docsearch_aliases'), django.contrib.postgres.indexes.GinIndex(fields=['vector'], name='docsearch_vector'), django.contrib.postgres.indexes.GinIndex(fields=['name_key'], name='docsearch_spelling', opclasses=('gin_trgm_ops',)), models.Index(fields=['entity_key'], name='docsearch_entity')],
                'constraints': [models.UniqueConstraint(fields=('document', 'key'), name='docsearch_entry_key')],
            },
        ),
    ]
