# Generated by Django 5.2.17 on 2026-09-25 07:31

from django.db import migrations, models


def check_duplicates(apps, schema_editor):
    entry = apps.get_model('search', 'SearchEntry')
    duplicates = list(entry.objects.using(schema_editor.connection.alias)
                      .filter(document__isnull=True).values('source', 'key')
                      .annotate(total=models.Count('pk')).filter(total__gt=1)[:10])
    if duplicates:
        raise ValueError('Duplicate catalogue search identities: {}'.format(duplicates))


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_extension_source'),
    ]

    operations = [
        migrations.RunPython(check_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='searchentry',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('source', 'key'), name='docsearch_catalog_key'),
        ),
    ]
