# Generated by Django 5.2.17 on 2026-09-11 03:54

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm is a trusted extension: the pgweb role can create it in the test database too.
        TrigramExtension(),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('component', models.CharField(db_index=True, max_length=64)),
                ('msgid', models.TextField()),
                ('msgid_plural', models.TextField(blank=True, default='')),
                ('msgctxt', models.TextField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('plural_forms', models.TextField(blank=True, default='')),
                ('original_forms', models.JSONField(blank=True, default=dict)),
                ('suggested_forms', models.JSONField(blank=True, default=dict)),
                ('suggestion_source', models.TextField(blank=True, default='')),
                ('calibration', models.JSONField(blank=True, default=dict)),
                ('old_assessment', models.CharField(default='unreviewed', max_length=16)),
                ('assessment_reason', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('plural_issue', models.TextField(blank=True, default='')),
                ('revision', models.CharField(max_length=64)),
                ('workbook_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', '待审'), ('approved', '已校对'), ('flagged', '标疑'), ('rejected', '否定')], default='pending', max_length=16)),
                ('forms', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('source_revision', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nls_message',
                'ordering': ('component', 'number'),
                'permissions': [('review', '可以校对消息翻译')],
                'indexes': [models.Index(fields=['component', 'status'], name='nls_message_component_status'), django.contrib.postgres.indexes.GistIndex(fields=['msgid'], name='nls_message_msgid_trgm', opclasses=('gist_trgm_ops',))],
            },
        ),
    ]
