# Generated by Django 5.2.17 on 2026-09-15 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pg_major',
            field=models.PositiveSmallIntegerField(db_index=True, default=19),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['pg_major', 'component', 'status'], name='nls_message_major_comp_status'),
        ),
    ]
