# Generated by Django 5.2.17 on 2026-09-20 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nls', '0002_message_pg_major_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('language', 'pg_major', 'component', 'number'), 'permissions': [('review', '可以校对消息翻译')]},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='nls_message_major_comp_status',
        ),
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(choices=[('zh_CN', '简体中文'), ('zh_TW', '繁體中文')], db_default='zh_CN', default='zh_CN', max_length=16),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['language', 'pg_major', 'component', 'status'], name='nls_lang_major_comp_status'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ['zh_CN', 'zh_TW'])), name='nls_message_language_valid'),
        ),
    ]
