# Generated by Django 5.2.10 on 2026-06-18 13:15

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersubmissions'),
        ('news', '0009_pinnednewsarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPostingEmbargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='禁发时段')),
                ('description', models.CharField(help_text='说明文字会向提交者和审核员显示，请勿填写敏感信息。', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': '新闻发布禁发时段',
                'verbose_name_plural': '新闻发布禁发时段',
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('duration', '&&')], name='unique_duration')],
                'ordering': ('duration',),
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(condition=models.Q(('modstate', 2), _negated=True), fields=['modstate'], name='idx_news_modstate_not_approved'),
        ),
    ]
