# Generated by Django 5.2.17 on 2026-09-10 06:15

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True)),
                ('date', models.DateField()),
                ('tier', models.SmallIntegerField(choices=[(1, '大新闻'), (2, '小新闻'), (3, '迷你')])),
                ('position', models.SmallIntegerField(default=0)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('author', models.TextField(blank=True, default='')),
                ('source', models.TextField(blank=True, default='')),
                ('source_date', models.DateField(blank=True, null=True)),
                ('image', models.TextField(blank=True, default='')),
                ('domain', models.CharField(default='pg', max_length=8)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('published', '已发布'), ('hidden', '已撤下')], default='published', max_length=10)),
                ('origin', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'db_table': 'info_item',
                'ordering': ('-date', 'tier', 'position', 'id'),
                'indexes': [models.Index(fields=['status', '-date', 'tier', 'position'], name='info_item_stream'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='info_item_vector')],
            },
        ),
    ]
